///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CrossBrowserTest.RecordingModules.CartPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmptyCart recording.
    /// </summary>
    [TestModule("b9b044a6-8306-4f96-864d-f7a46404348b", ModuleType.Recording, 1)]
    public partial class EmptyCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CrossBrowserTest.RXTrainingWebAppRepository repository.
        /// </summary>
        public static global::CrossBrowserTest.RXTrainingWebAppRepository repo = global::CrossBrowserTest.RXTrainingWebAppRepository.Instance;

        static EmptyCart instance = new EmptyCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmptyCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmptyCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JupiterPrimeGoogleChrome.CartPage.EmptyCartButton' at 94;28.", repo.JupiterPrimeGoogleChrome.CartPage.EmptyCartButtonInfo, new RecordItemIndex(0));
            repo.JupiterPrimeGoogleChrome.CartPage.EmptyCartButton.Click("94;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JupiterPrimeGoogleChrome.CartPage.ModalYesButton' at 74;21.", repo.JupiterPrimeGoogleChrome.CartPage.ModalYesButtonInfo, new RecordItemIndex(1));
            repo.JupiterPrimeGoogleChrome.CartPage.ModalYesButton.Click("74;21");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
