///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CrossBrowserTest.RecordingModules.CartPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateProductInCart recording.
    /// </summary>
    [TestModule("560dca42-667f-4e04-92c6-7b3072e54310", ModuleType.Recording, 1)]
    public partial class ValidateProductInCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CrossBrowserTest.RXTrainingWebAppRepository repository.
        /// </summary>
        public static global::CrossBrowserTest.RXTrainingWebAppRepository repo = global::CrossBrowserTest.RXTrainingWebAppRepository.Instance;

        static ValidateProductInCart instance = new ValidateProductInCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateProductInCart()
        {
            varExpectedProductNameInCart = "puppy";
            varProudctNameInCart = "puppy";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateProductInCart Instance
        {
            get { return instance; }
        }

#region Variables

        string _varExpectedProductNameInCart;

        /// <summary>
        /// Gets or sets the value of variable varExpectedProductNameInCart.
        /// </summary>
        [TestVariable("197664db-000a-4c65-aae0-7e9ec2135b18")]
        public string varExpectedProductNameInCart
        {
            get { return _varExpectedProductNameInCart; }
            set { _varExpectedProductNameInCart = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varProudctNameInCart.
        /// </summary>
        [TestVariable("4dba7918-bc36-40cc-a7c8-f858e4c60eeb")]
        public string varProudctNameInCart
        {
            get { return repo.varProudctNameInCart; }
            set { repo.varProudctNameInCart = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'JupiterPrimeGoogleChrome.CartPage.ProductName'.", repo.JupiterPrimeGoogleChrome.CartPage.ProductNameInfo, new RecordItemIndex(0));
            repo.JupiterPrimeGoogleChrome.CartPage.ProductName.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varExpectedProductNameInCart) on item 'JupiterPrimeGoogleChrome.CartPage.ProductName'.", repo.JupiterPrimeGoogleChrome.CartPage.ProductNameInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.JupiterPrimeGoogleChrome.CartPage.ProductNameInfo, "Text", varExpectedProductNameInCart);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
