///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CrossBrowserTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RXTrainingWebAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6745b119-3268-41d8-9bfe-5037074397e8")]
    public partial class RXTrainingWebAppRepository : RepoGenBaseFolder
    {
        static RXTrainingWebAppRepository instance = new RXTrainingWebAppRepository();
        RXTrainingWebAppRepositoryFolders.JupiterPrimeGoogleChromeAppFolder _jupiterprimegooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the RXTrainingWebAppRepository element repository.
        /// </summary>
        [RepositoryFolder("6745b119-3268-41d8-9bfe-5037074397e8")]
        public static RXTrainingWebAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RXTrainingWebAppRepository() 
            : base("RXTrainingWebAppRepository", "/", null, 0, false, "6745b119-3268-41d8-9bfe-5037074397e8", ".\\RepositoryImages\\RXTrainingWebAppRepository6745b119.rximgres")
        {
            _jupiterprimegooglechrome = new RXTrainingWebAppRepositoryFolders.JupiterPrimeGoogleChromeAppFolder(this);
        }

#region Variables

        string _varProductName = "puppy";

        /// <summary>
        /// Gets or sets the value of variable varProductName.
        /// </summary>
        [TestVariable("d91b8e00-09c6-4379-98ba-277e8a4ba478")]
        public string varProductName
        {
            get { return _varProductName; }
            set { _varProductName = value; }
        }

        string _varProudctNameInCart = "puppy";

        /// <summary>
        /// Gets or sets the value of variable varProudctNameInCart.
        /// </summary>
        [TestVariable("4dba7918-bc36-40cc-a7c8-f858e4c60eeb")]
        public string varProudctNameInCart
        {
            get { return _varProudctNameInCart; }
            set { _varProudctNameInCart = value; }
        }

        string _varAddButtonName = "Add one puppy to cart";

        /// <summary>
        /// Gets or sets the value of variable varAddButtonName.
        /// </summary>
        [TestVariable("d1fd77c8-62f5-46b4-a4f5-684266013fdc")]
        public string varAddButtonName
        {
            get { return _varAddButtonName; }
            set { _varAddButtonName = value; }
        }

        string _varAddProductButtonName = "Add one puppy to cart";

        /// <summary>
        /// Gets or sets the value of variable varAddProductButtonName.
        /// </summary>
        [TestVariable("3ada7aeb-4004-451f-8388-78a644226834")]
        public string varAddProductButtonName
        {
            get { return _varAddProductButtonName; }
            set { _varAddProductButtonName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6745b119-3268-41d8-9bfe-5037074397e8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The JupiterPrimeGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("2bd0f3e6-4055-480e-9397-431b4558843c")]
        public virtual RXTrainingWebAppRepositoryFolders.JupiterPrimeGoogleChromeAppFolder JupiterPrimeGoogleChrome
        {
            get { return _jupiterprimegooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RXTrainingWebAppRepositoryFolders
    {
        /// <summary>
        /// The JupiterPrimeGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("2bd0f3e6-4055-480e-9397-431b4558843c")]
        public partial class JupiterPrimeGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RXTrainingWebAppRepositoryFolders.MenuFolder _menu;
            RXTrainingWebAppRepositoryFolders.CartPageFolder _cartpage;
            RXTrainingWebAppRepositoryFolders.CheckoutPageFolder _checkoutpage;
            RXTrainingWebAppRepositoryFolders.ShopPageFolder _shoppage;

            /// <summary>
            /// Creates a new JupiterPrimeGoogleChrome  folder.
            /// </summary>
            public JupiterPrimeGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JupiterPrimeGoogleChrome", "/form[@title>'JupiterPrime']", parentFolder, 30000, null, true, "2bd0f3e6-4055-480e-9397-431b4558843c", "")
            {
                _menu = new RXTrainingWebAppRepositoryFolders.MenuFolder(this);
                _cartpage = new RXTrainingWebAppRepositoryFolders.CartPageFolder(this);
                _checkoutpage = new RXTrainingWebAppRepositoryFolders.CheckoutPageFolder(this);
                _shoppage = new RXTrainingWebAppRepositoryFolders.ShopPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2bd0f3e6-4055-480e-9397-431b4558843c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2bd0f3e6-4055-480e-9397-431b4558843c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Menu folder.
            /// </summary>
            [RepositoryFolder("0591abfe-e005-4701-849e-d1e5a3528b39")]
            public virtual RXTrainingWebAppRepositoryFolders.MenuFolder Menu
            {
                get { return _menu; }
            }

            /// <summary>
            /// The CartPage folder.
            /// </summary>
            [RepositoryFolder("e0893e39-57c2-4e59-851b-3147275b7622")]
            public virtual RXTrainingWebAppRepositoryFolders.CartPageFolder CartPage
            {
                get { return _cartpage; }
            }

            /// <summary>
            /// The CheckoutPage folder.
            /// </summary>
            [RepositoryFolder("2b030481-958e-4240-aa15-411a1a18f682")]
            public virtual RXTrainingWebAppRepositoryFolders.CheckoutPageFolder CheckoutPage
            {
                get { return _checkoutpage; }
            }

            /// <summary>
            /// The ShopPage folder.
            /// </summary>
            [RepositoryFolder("d0100016-3a7a-481d-9177-1552b94cd2dc")]
            public virtual RXTrainingWebAppRepositoryFolders.ShopPageFolder ShopPage
            {
                get { return _shoppage; }
            }
        }

        /// <summary>
        /// The MenuFolder folder.
        /// </summary>
        [RepositoryFolder("0591abfe-e005-4701-849e-d1e5a3528b39")]
        public partial class MenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menushopInfo;

            /// <summary>
            /// Creates a new Menu  folder.
            /// </summary>
            public MenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Menu", "", parentFolder, 0, null, false, "0591abfe-e005-4701-849e-d1e5a3528b39", "")
            {
                _menushopInfo = new RepoItemInfo(this, "MenuShop", "?/container[@automationid='root']//link[@automationid='menu-shop']", "", 30000, null, "8f662f39-4cd7-4ea4-950c-e362b3bf0d63");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0591abfe-e005-4701-849e-d1e5a3528b39")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuShop item.
            /// </summary>
            [RepositoryItem("8f662f39-4cd7-4ea4-950c-e362b3bf0d63")]
            public virtual Ranorex.Link MenuShop
            {
                get
                {
                    return _menushopInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The MenuShop item info.
            /// </summary>
            [RepositoryItemInfo("8f662f39-4cd7-4ea4-950c-e362b3bf0d63")]
            public virtual RepoItemInfo MenuShopInfo
            {
                get
                {
                    return _menushopInfo;
                }
            }
        }

        /// <summary>
        /// The CartPageFolder folder.
        /// </summary>
        [RepositoryFolder("e0893e39-57c2-4e59-851b-3147275b7622")]
        public partial class CartPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productnameInfo;
            RepoItemInfo _modalyesbuttonInfo;
            RepoItemInfo _checkoutbuttonInfo;
            RepoItemInfo _emptycartbuttonInfo;

            /// <summary>
            /// Creates a new CartPage  folder.
            /// </summary>
            public CartPageFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPage", "", parentFolder, 0, null, false, "e0893e39-57c2-4e59-851b-3147275b7622", "")
            {
                _productnameInfo = new RepoItemInfo(this, "ProductName", "?/?/?/?/table[@automationid='cart-items']//text[@name=$varProudctNameInCart]", "", 30000, null, "8647a075-016e-42ee-b18b-20b9e81f7bcb");
                _modalyesbuttonInfo = new RepoItemInfo(this, "ModalYesButton", "?//element[@automationid='empty-cart-modal']/button[@automationid='modal-yes-button']", "", 30000, null, "87942045-1102-484b-b598-818bc0ab464c");
                _checkoutbuttonInfo = new RepoItemInfo(this, "CheckoutButton", "?//button[@automationid='checkout-button']", "", 30000, null, "616a6120-4897-4534-9bde-9cdd1485a313");
                _emptycartbuttonInfo = new RepoItemInfo(this, "EmptyCartButton", "?//button[@automationid='empty-cart-button']", "", 30000, null, "c91b988d-f279-4e0e-916c-9c7c3a9a9774");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0893e39-57c2-4e59-851b-3147275b7622")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductName item.
            /// </summary>
            [RepositoryItem("8647a075-016e-42ee-b18b-20b9e81f7bcb")]
            public virtual Ranorex.Text ProductName
            {
                get
                {
                    return _productnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProductName item info.
            /// </summary>
            [RepositoryItemInfo("8647a075-016e-42ee-b18b-20b9e81f7bcb")]
            public virtual RepoItemInfo ProductNameInfo
            {
                get
                {
                    return _productnameInfo;
                }
            }

            /// <summary>
            /// The ModalYesButton item.
            /// </summary>
            [RepositoryItem("87942045-1102-484b-b598-818bc0ab464c")]
            public virtual Ranorex.Button ModalYesButton
            {
                get
                {
                    return _modalyesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ModalYesButton item info.
            /// </summary>
            [RepositoryItemInfo("87942045-1102-484b-b598-818bc0ab464c")]
            public virtual RepoItemInfo ModalYesButtonInfo
            {
                get
                {
                    return _modalyesbuttonInfo;
                }
            }

            /// <summary>
            /// The CheckoutButton item.
            /// </summary>
            [RepositoryItem("616a6120-4897-4534-9bde-9cdd1485a313")]
            public virtual Ranorex.Button CheckoutButton
            {
                get
                {
                    return _checkoutbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CheckoutButton item info.
            /// </summary>
            [RepositoryItemInfo("616a6120-4897-4534-9bde-9cdd1485a313")]
            public virtual RepoItemInfo CheckoutButtonInfo
            {
                get
                {
                    return _checkoutbuttonInfo;
                }
            }

            /// <summary>
            /// The EmptyCartButton item.
            /// </summary>
            [RepositoryItem("c91b988d-f279-4e0e-916c-9c7c3a9a9774")]
            public virtual Ranorex.Button EmptyCartButton
            {
                get
                {
                    return _emptycartbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EmptyCartButton item info.
            /// </summary>
            [RepositoryItemInfo("c91b988d-f279-4e0e-916c-9c7c3a9a9774")]
            public virtual RepoItemInfo EmptyCartButtonInfo
            {
                get
                {
                    return _emptycartbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CheckoutPageFolder folder.
        /// </summary>
        [RepositoryFolder("2b030481-958e-4240-aa15-411a1a18f682")]
        public partial class CheckoutPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txttotalpriceInfo;

            /// <summary>
            /// Creates a new CheckoutPage  folder.
            /// </summary>
            public CheckoutPageFolder(RepoGenBaseFolder parentFolder) :
                    base("CheckoutPage", "", parentFolder, 0, null, false, "2b030481-958e-4240-aa15-411a1a18f682", "")
            {
                _txttotalpriceInfo = new RepoItemInfo(this, "TxtTotalPrice", "?//?/?//?/?/?/?/table[@automationid='cart-items']//?/container[@automationid='footer-total']/?/?/text", "", 30000, null, "b5b78802-d67f-4d4b-9b37-dbcb99cf4749");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b030481-958e-4240-aa15-411a1a18f682")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtTotalPrice item.
            /// </summary>
            [RepositoryItem("b5b78802-d67f-4d4b-9b37-dbcb99cf4749")]
            public virtual Ranorex.Text TxtTotalPrice
            {
                get
                {
                    return _txttotalpriceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtTotalPrice item info.
            /// </summary>
            [RepositoryItemInfo("b5b78802-d67f-4d4b-9b37-dbcb99cf4749")]
            public virtual RepoItemInfo TxtTotalPriceInfo
            {
                get
                {
                    return _txttotalpriceInfo;
                }
            }
        }

        /// <summary>
        /// The ShopPageFolder folder.
        /// </summary>
        [RepositoryFolder("d0100016-3a7a-481d-9177-1552b94cd2dc")]
        public partial class ShopPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addonepproducttocartInfo;
            RepoItemInfo _mycartbuttonInfo;

            /// <summary>
            /// Creates a new ShopPage  folder.
            /// </summary>
            public ShopPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ShopPage", "", parentFolder, 0, null, false, "d0100016-3a7a-481d-9177-1552b94cd2dc", "")
            {
                _addonepproducttocartInfo = new RepoItemInfo(this, "AddOnepProductToCart", "*/descendant-or-self::*/*/button[@name=$varAddProductButtonName]", "", 30000, null, "358ff01a-3a86-463f-a0fb-684833b38d13");
                _mycartbuttonInfo = new RepoItemInfo(this, "MyCartButton", "?/?/?/container[@automationid='app-root']/container[3]/button[@automationid='my-cart-button']", "", 30000, null, "d43dd59a-efc6-42db-9abc-66fc9c66da50");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0100016-3a7a-481d-9177-1552b94cd2dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddOnepProductToCart item.
            /// </summary>
            [RepositoryItem("358ff01a-3a86-463f-a0fb-684833b38d13")]
            public virtual Ranorex.Button AddOnepProductToCart
            {
                get
                {
                    return _addonepproducttocartInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddOnepProductToCart item info.
            /// </summary>
            [RepositoryItemInfo("358ff01a-3a86-463f-a0fb-684833b38d13")]
            public virtual RepoItemInfo AddOnepProductToCartInfo
            {
                get
                {
                    return _addonepproducttocartInfo;
                }
            }

            /// <summary>
            /// The MyCartButton item.
            /// </summary>
            [RepositoryItem("d43dd59a-efc6-42db-9abc-66fc9c66da50")]
            public virtual Ranorex.Button MyCartButton
            {
                get
                {
                    return _mycartbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MyCartButton item info.
            /// </summary>
            [RepositoryItemInfo("d43dd59a-efc6-42db-9abc-66fc9c66da50")]
            public virtual RepoItemInfo MyCartButtonInfo
            {
                get
                {
                    return _mycartbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
