///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CrossBrowserTest.RecordingModules.CheckOutPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateTotalPrice recording.
    /// </summary>
    [TestModule("13548bcc-677a-4c7e-bd7d-35e2541a523d", ModuleType.Recording, 1)]
    public partial class ValidateTotalPrice : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CrossBrowserTest.RXTrainingWebAppRepository repository.
        /// </summary>
        public static global::CrossBrowserTest.RXTrainingWebAppRepository repo = global::CrossBrowserTest.RXTrainingWebAppRepository.Instance;

        static ValidateTotalPrice instance = new ValidateTotalPrice();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateTotalPrice()
        {
            varActualTotalPrice = "$2,198.00";
            varExpectTotalPrice = "$2,198.00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateTotalPrice Instance
        {
            get { return instance; }
        }

#region Variables

        string _varActualTotalPrice;

        /// <summary>
        /// Gets or sets the value of variable varActualTotalPrice.
        /// </summary>
        [TestVariable("b79fb5b5-b092-4227-9029-ecf85256f809")]
        public string varActualTotalPrice
        {
            get { return _varActualTotalPrice; }
            set { _varActualTotalPrice = value; }
        }

        string _varExpectTotalPrice;

        /// <summary>
        /// Gets or sets the value of variable varExpectTotalPrice.
        /// </summary>
        [TestVariable("935ee680-21ff-41ed-8040-ead5f8e09929")]
        public string varExpectTotalPrice
        {
            get { return _varExpectTotalPrice; }
            set { _varExpectTotalPrice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Name='$1,099.00') on item 'JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPrice'.", repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPriceInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPriceInfo, "Name", "$1,099.00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varExpectTotalPrice) on item 'JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPrice'.", repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPriceInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPriceInfo, "Text", varExpectTotalPrice);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPrice' and assigning its value to variable 'varActualTotalPrice'.", repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPriceInfo, new RecordItemIndex(2));
            varActualTotalPrice = repo.JupiterPrimeGoogleChrome.CheckoutPage.TxtTotalPrice.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varActualTotalPrice, new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
