///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CrossBrowserTest.RecordingModules.ShopPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddProductToCart recording.
    /// </summary>
    [TestModule("b3ca57b5-f566-4bb4-87a4-8a98f557adfe", ModuleType.Recording, 1)]
    public partial class AddProductToCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CrossBrowserTest.RXTrainingWebAppRepository repository.
        /// </summary>
        public static global::CrossBrowserTest.RXTrainingWebAppRepository repo = global::CrossBrowserTest.RXTrainingWebAppRepository.Instance;

        static AddProductToCart instance = new AddProductToCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddProductToCart()
        {
            varProductName = "puppy";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddProductToCart Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varAddProductButtonName.
        /// </summary>
        [TestVariable("3ada7aeb-4004-451f-8388-78a644226834")]
        public string varAddProductButtonName
        {
            get { return repo.varAddProductButtonName; }
            set { repo.varAddProductButtonName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varProductName.
        /// </summary>
        [TestVariable("48ee1f95-cc92-4ae7-8a1d-250fd99215dc")]
        public string varProductName
        {
            get { return repo.varProductName; }
            set { repo.varProductName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCart'.", repo.JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCartInfo, new RecordItemIndex(0));
            repo.JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCart.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCart'.", repo.JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCartInfo, new RecordItemIndex(1));
            repo.JupiterPrimeGoogleChrome.ShopPage.AddOnepProductToCart.Press();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
